"""Add avatar_url to User

Revision ID: 82688b4af8c9
Revises: 23a3d1e2e86a
Create Date: 2025-06-23 01:44:59.984400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82688b4af8c9'
down_revision = '23a3d1e2e86a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.String(length=50), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_column('frequency')

    # ### end Alembic commands ###
